/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FeatureCard: typeof import('./src/components/common/FeatureCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    VButton: typeof import('./src/components/common/VButton.vue')['default']
    VCard: typeof import('./src/components/common/VCard.vue')['default']
    VCheckbox: typeof import('./src/components/common/VCheckbox.vue')['default']
    VIcon: typeof import('./src/components/VIcon.vue')['default']
    VLoader: typeof import('./src/components/common/VLoader.vue')['default']
    VModal: typeof import('./src/components/common/VModal.vue')['default']
    VSearch: typeof import('./src/components/common/VSearch.vue')['default']
    VSwitch: typeof import('./src/components/common/VSwitch.vue')['default']
  }
}
